name: elasticsearch

on:
  push:
    paths:
      - 'docker/elasticsearch/**'
      - '.github/workflows/elasticsearch.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: isec-tut
          password: ${{ github.token }}

      - name: Build and push - elasticsearch
        uses: docker/build-push-action@v5
        with:
          context: ./docker/elasticsearch
          file: ./docker/elasticsearch/Dockerfile
          tags: |
            ghcr.io/isec-tut/containers/elasticsearch
          platforms: linux/amd64
          push: true
