name: kubectl

on:
  push:
    paths:
      - 'docker/kubectl/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push - kubectl
        uses: docker/build-push-action@v5
        with:
          context: ./docker/kubectl
          file: ./docker/kubectl/Dockerfile
          tags: |
            ghcr.io/isec-tut/containers/kubectl
          platforms: linux/amd64
          push: true
